package entkt.codegen

/**
 * Format a [MemberCollision] as a single-line diagnostic suitable
 * for appending to `ValidationResult.errors`: schema, artifact,
 * generated name, kind hint, and every contributing source.
 *
 * Two-source shape (the common case):
 *
 *   Schema 'Article': ArticleUpdateMutationView member 'unsetWriter'
 *   is generated by field 'unset_writer' and by unset method for
 *   field-backed FK edge 'author'
 *
 * Three-or-more-source shape (rare but possible):
 *
 *   Schema 'Post': PostUpdateMutationView member 'unsetName' is
 *   generated by 3 conflicting sources: field 'name'; field
 *   'unset_name'; unset method for FK 'name'
 *
 * A "framework-member" hint is appended when at least one source
 * is a fixed framework member, to flag that renaming the
 * user-controlled side is the path to resolution (the framework
 * member can't be renamed by the schema author).
 */
internal fun formatMemberCollisionDiagnostic(collision: MemberCollision): String {
    val sources = collision.sources
    val kindHint = collision.sources.firstOrNull()?.kind?.let { kindDescriptor(it) } ?: "member"

    val base = buildString {
        append("Schema '")
        append(collision.schema)
        append("': ")
        append(collision.artifact)
        append(' ')
        append(kindHint)
        append(" '")
        append(collision.name)
        append("' is generated by ")
        if (sources.size == 2) {
            append(sources[0].source)
            append(" and by ")
            append(sources[1].source)
        } else {
            append(sources.size)
            append(" conflicting sources: ")
            append(sources.joinToString("; ") { it.source })
        }
    }

    val frameworkHint = if (sources.any { isFrameworkMember(it.source) }) {
        " — one of the conflicting sources is a fixed framework member; " +
            "rename the user-declared field/edge to resolve"
    } else {
        ""
    }

    return base + frameworkHint
}

/**
 * Phrase that fits the "X 'name' is generated by ..." sentence. We
 * blend kinds when sources disagree (a property vs. a function on
 * the same artifact still has to be reported as a collision per
 * the contract; "member" is the neutral wording).
 */
private fun kindDescriptor(kind: GeneratedMemberKind): String = when (kind) {
    GeneratedMemberKind.PROPERTY -> "property"
    GeneratedMemberKind.FUNCTION -> "method"
    GeneratedMemberKind.NESTED_TYPE -> "nested type"
    GeneratedMemberKind.CONSTRUCTOR_PARAMETER -> "constructor parameter"
}

/**
 * Heuristic: a source is "framework-owned" if its phrasing starts
 * with `fixed` or `data-class synthesized`. Keep this aligned with
 * how `BuildMemberManifest.kt` phrases each fixed-member source —
 * if the source-phrase convention changes there, update both
 * places at once.
 */
private fun isFrameworkMember(source: String): Boolean =
    source.startsWith("fixed ") || source.startsWith("data-class synthesized")
