spring:
  application:
    name: entkt-spring-example
  datasource:
    url: jdbc:postgresql://localhost:5432/entkt_example
    username: postgres
    password: postgres
  flyway:
    locations: filesystem:db/migrations
