@file:OptIn(org.jetbrains.kotlin.compiler.plugin.ExperimentalCompilerApi::class)

package entkt.codegen

import com.tschuchort.compiletesting.JvmCompilationResult
import com.tschuchort.compiletesting.KotlinCompilation
import com.tschuchort.compiletesting.SourceFile
import entkt.schema.EntId
import entkt.schema.EntSchema
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertTrue

private class Attachment : EntSchema("attachments") {
    override fun id() = EntId.long()
    val payload = bytes("payload")
    val thumb = bytes("thumb").nullable()
    val label = string("label")
}

/**
 * Compiles and executes the generated entity for a BYTES schema to pin
 * content-based equality: Kotlin's data-class equals compares ByteArray
 * properties by reference, so the generator overrides equals/hashCode
 * with contentEquals/contentHashCode. Two separately constructed
 * entities holding equal bytes must compare equal and hash alike.
 */
class BytesEqualityCompileTest {

    private fun compile(): JvmCompilationResult {
        val schema = Attachment()
        schema.finalize(mapOf<kotlin.reflect.KClass<out EntSchema>, EntSchema>(schema::class to schema))
        val sources = EntGenerator("com.example.ent")
            .generate(listOf(SchemaInput("Attachment", schema)))
            .map { SourceFile.kotlin("${it.name}.kt", it.toString()) }
        return KotlinCompilation().apply {
            this.sources = sources
            inheritClassPath = true
            kotlincArguments = listOf("-Xskip-metadata-version-check")
            jvmTarget = "17"
            messageOutputStream = java.io.OutputStream.nullOutputStream()
        }.compile()
    }

    @Test
    fun `entities with equal byte content are equal and hash alike`() {
        val result = compile()
        assertEquals(
            KotlinCompilation.ExitCode.OK,
            result.exitCode,
            "Expected the generated bytes entity to compile, got:\n${result.messages}",
        )

        val cls = result.classLoader.loadClass("com.example.ent.Attachment")
        // Kotlin emits a synthetic defaults-overload constructor alongside
        // the primary; select the primary by its exact parameter count.
        // (id: Long, payload: ByteArray, thumb: ByteArray?, label: String)
        val ctor = cls.constructors.single { it.parameterCount == 4 }
        fun make(payload: ByteArray, thumb: ByteArray?) =
            ctor.newInstance(1L, payload, thumb, "doc")

        val a = make(byteArrayOf(1, 2, 3), byteArrayOf(9))
        val b = make(byteArrayOf(1, 2, 3), byteArrayOf(9))
        assertTrue(a == b, "Entities with identical byte content should be equal")
        assertEquals(a.hashCode(), b.hashCode(), "Equal entities should hash alike")

        val differentBytes = make(byteArrayOf(1, 2, 4), byteArrayOf(9))
        assertFalse(a == differentBytes, "Entities with different byte content should not be equal")

        val nullThumbA = make(byteArrayOf(1), null)
        val nullThumbB = make(byteArrayOf(1), null)
        assertTrue(nullThumbA == nullThumbB, "Null bytes fields should compare equal")
        assertFalse(nullThumbA == a, "Null vs non-null bytes fields should not be equal")
    }
}