package entkt.codegen

import entkt.schema.EntId
import entkt.schema.EntSchema
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertTrue
import kotlin.test.fail

/**
 * end-to-end coverage for generated-member collision checks's
 * generated-member-name collision detection. Exercises
 * `SchemaInspector.validate` over schemas that should and should
 * not produce a member-collision diagnostic.
 *
 * Negative-test pattern: schemas that today pass the existing
 * column-collision check (which fires during finalize()) but
 * trip the new member-collision check.
 */
class MemberCollisionValidationTest {

    private fun validate(vararg schemas: Pair<String, EntSchema>): List<String> {
        val inputs = schemas.map { SchemaInput(it.second) }
        val result = SchemaInspector.validate(inputs)
        return result.errors
    }

    /**
     * Match the generated-member collision checks diagnostic shape. The new format always
     * includes `<artifact> <kind> '<member>' is generated by`,
     * so the substring `is generated by` plus the artifact and
     * quoted member name uniquely identify a manifest-derived
     * diagnostic. This guards against future regressions where
     * a less-precise pass might satisfy a naive `contains` check.
     */
    private fun assertCollision(
        errors: List<String>,
        artifact: String,
        memberName: String,
        message: String = "expected a $artifact.$memberName collision",
    ) {
        val match = errors.firstOrNull {
            it.contains(artifact) && it.contains("'$memberName'") && it.contains("is generated by")
        }
        if (match == null) {
            fail("$message\nGot errors:\n${errors.joinToString("\n") { "  - $it" }}")
        }
    }

    // ──────────────────────────────────────────────────────────────
    // Collision case: field vs. generated unset{Property}() collision
    // ──────────────────────────────────────────────────────────────

    @Test
    fun `field 'unset_name' collides with the unset method generated for field 'name'`() {
        class S : EntSchema("s", clientName = "ses") {
            override fun id() = EntId.long()
            val name by string("name")
            val unsetName by bool("unset_name")
        }

        val errors = validate("S" to S())
        // The clash lands on the update mutation view (where unset
        // methods live) and on the update builder.
        assertCollision(errors, "SUpdateMutationView", "unsetName")
    }

    // ──────────────────────────────────────────────────────────────
    // Collision case: field named `copy` colliding with
    // data-class synthesized `copy`.
    // ──────────────────────────────────────────────────────────────

    @Test
    fun `field 'copy' collides with the data-class synthesized copy()`() {
        class S : EntSchema("s", clientName = "ses") {
            override fun id() = EntId.long()
            val copy by string("copy")
        }

        val errors = validate("S" to S())
        assertCollision(errors, "S", "copy")
        // Framework-member hint should be present since `copy`
        // is data-class synthesized.
        val matching = errors.first { "S " in it && "'copy'" in it }
        assertTrue("framework member" in matching, "framework hint expected: $matching")
    }

    // ──────────────────────────────────────────────────────────────
    // Collision case: field that would generate `component1`
    // colliding with the synthesized component function.
    // ──────────────────────────────────────────────────────────────

    @Test
    fun `field 'component1' collides with the data-class synthesized component1()`() {
        class S : EntSchema("s", clientName = "ses") {
            override fun id() = EntId.long()
            val component1 by string("component1")
            // Some filler to ensure constructor arity reaches >= 1.
            val title by string("title")
        }

        val errors = validate("S" to S())
        assertCollision(errors, "S", "component1")
    }

    // ──────────────────────────────────────────────────────────────
    // Collision case: field named `edges` colliding with entity
    // `edges`. Caught by the manifest now that the old
    // `validateMemberNames` pass has been retired.
    // ──────────────────────────────────────────────────────────────

    @Test
    fun `field 'edges' collides with the fixed entity 'edges' accessor`() {
        class S : EntSchema("s", clientName = "ses") {
            override fun id() = EntId.long()
            val edges by string("edges")
        }

        val errors = validate("S" to S())
        assertCollision(errors, "S", "edges")
    }
    // Collision case: field whose generated name matches a
    // fixed builder member (`saveAndLoad`).
    // ──────────────────────────────────────────────────────────────

    @Test
    fun `field 'save_and_load' collides with the fixed update terminal only`() {
        class S : EntSchema("s", clientName = "ses") {
            override fun id() = EntId.long()
            val saveAndLoad by bool("save_and_load")
        }

        val errors = validate("S" to S())
        // Create drafts contain state only, so this name is available there.
        assertCollision(errors, "SUpdate", "saveAndLoad")
    }

    // ──────────────────────────────────────────────────────────────
    // Collision case: field named `from_row` colliding with
    // companion `fromRow`. The collision IS real — the entity
    // companion gets per-field column refs alongside the fixed
    // `fromRow()` decoder, both on the same `${Entity}.Companion`
    // artifact.
    // ──────────────────────────────────────────────────────────────

    @Test
    fun `field 'from_row' collides with the companion 'fromRow' decoder`() {
        class S : EntSchema("s", clientName = "ses") {
            override fun id() = EntId.long()
            val fromRow by string("from_row")
        }

        val errors = validate("S" to S())
        // The column ref `S.Companion.fromRow` (PROPERTY, from
        // the field) clashes with the fixed `S.Companion.fromRow()`
        // function. Manifest detects both on the `S.Companion`
        // artifact.
        assertCollision(errors, "S.Companion", "fromRow")
    }

    // ──────────────────────────────────────────────────────────────
    // Collision case: diagnostic includes the schema name,
    // generated artifact, generated member name, and both sources.
    // ──────────────────────────────────────────────────────────────

    @Test
    fun `diagnostic includes schema name, artifact, member name, and both contributing sources`() {
        class S : EntSchema("s", clientName = "ses") {
            override fun id() = EntId.long()
            val name by string("name")
            val unsetName by bool("unset_name")
        }

        val errors = validate("S" to S())
        val diag = errors.first { it.contains("SUpdateMutationView") && it.contains("'unsetName'") }
        assertTrue("Schema 'S'" in diag, "Diagnostic should name the schema: $diag")
        assertTrue("SUpdateMutationView" in diag, "Diagnostic should name the artifact: $diag")
        assertTrue("'unsetName'" in diag, "Diagnostic should name the member: $diag")
        assertTrue(
            "field 'unsetName'" in diag,
            "Diagnostic should name the *declaration*, since renaming it is the fix " +
                "(the storage column 'unset_name' is not what the author changes): $diag",
        )
        assertTrue(
            "unset method for field 'name'" in diag,
            "Diagnostic should reference the generated unset method source: $diag",
        )
    }

    // ──────────────────────────────────────────────────────────────
    // Collision case: field named `pending_edges`
    // collides with the fixed `pendingEdges` member on the update
    // mutation view, regardless of whether the schema has any
    // helper-eligible M2M edge. The interface emits the property
    // unconditionally, so a non-M2M schema is just as much at risk
    // as an M2M one.
    // ──────────────────────────────────────────────────────────────

    @Test
    fun `field 'pending_edges' collides with the fixed UpdateMutationView pendingEdges member`() {
        class S : EntSchema("s", clientName = "ses") {
            override fun id() = EntId.long()
            val pendingEdges by string("pending_edges")
        }

        val errors = validate("S" to S())
        assertCollision(errors, "SUpdateMutationView", "pendingEdges")
    }

    // ──────────────────────────────────────────────────────────────
    // Collision cases are documented as not-V1-
    // triggerable. Schema-level name validation enforces snake_case
    // for both field and edge names; a scalar whose camelCased
    // property would match an implicit FK's `${edgeName}Id`
    // property MUST use the same snake_case column as the FK
    // (e.g. `author_id` ↔ `author_id`), which fails at the
    // column-collision layer before the manifest sees it. The
    // same constraint applies to field-backed FKs in V1 because
    // the FK property derives from the backing column, not yet
    // from a Kotlin val name. Once declaration-name capture ships declaration-name
    // capture, the FK property name can diverge from the column
    // and these cases become triggerable; the manifest already
    // handles them and will add the test cases then.
    // ──────────────────────────────────────────────────────────────

    // ──────────────────────────────────────────────────────────────
    // Collision case: companion edge ref name collides with
    // companion FK column ref name. The implicit FK for
    // `belongsTo<X>("author")` produces a column ref named
    // `authorId` on the companion (toCamelCase("author_id"));
    // a `hasMany` edge declared with name "author_id"
    // (snake_case-valid) produces an edge ref also named
    // `authorId` on the same companion. Both share the
    // `${Schema}.Companion` artifact.
    // (The Edges *class* artifact for non-belongsTo edge accessors
    // is deferred — this test covers the companion-only
    // V1 slice of "edge ref vs FK ref" collisions.)
    // ──────────────────────────────────────────────────────────────

    @Test
    fun `edge ref collides with implicit FK column ref on the companion`() {
        val errors = validate(
            "CompanionAuthor" to CompanionAuthor(),
            "CompanionReader" to CompanionReader(),
            "CompanionPost" to CompanionPost(),
        )
        assertCollision(errors, "CompanionPost.Companion", "authorId")
    }

    // ──────────────────────────────────────────────────────────────
    // The generated hook-facing adapter properties (`_beforeSaveView`,
    // `_createMutationView` on Create; `_mutationView`,
    // `_capturedPendingEdges` on Update) all use a leading `_`.
    //
    // Under the declaration-name contract a schema can no longer reach
    // them: declaration names must be lower-camel identifiers, so `_` is
    // reserved for the framework and this whole class of collision is
    // structurally unreachable rather than merely detected. The
    // manifest still carries these members so a *future generated*
    // member colliding with them is caught.
    //
    // See `docs/implemented-features/schema/schema-declaration-api-names.md`.
    // ──────────────────────────────────────────────────────────────

    @Test
    fun `declaration names cannot claim the framework's reserved underscore prefix`() {
        // One object expression per reserved name: a declaration name is
        // a compile-time property name, so this cannot be table-driven.
        val cases = listOf<Pair<String, () -> Unit>>(
            "_beforeSaveView" to {
                object : EntSchema("reserved_a", clientName = "reservedAs") {
                    override fun id() = EntId.long()
                    val _beforeSaveView by long("backing_col")
                }
                Unit
            },
            "_createMutationView" to {
                object : EntSchema("reserved_b", clientName = "reservedBs") {
                    override fun id() = EntId.long()
                    val _createMutationView by long("backing_col")
                }
                Unit
            },
            "_mutationView" to {
                object : EntSchema("reserved_c", clientName = "reservedCs") {
                    override fun id() = EntId.long()
                    val _mutationView by long("backing_col")
                }
                Unit
            },
            "_capturedPendingEdges" to {
                object : EntSchema("reserved_d", clientName = "reservedDs") {
                    override fun id() = EntId.long()
                    val _capturedPendingEdges by long("backing_col")
                }
                Unit
            },
        )
        for ((name, build) in cases) {
            val err = assertFailsWith<IllegalArgumentException>("expected reject for '$name'", build)
            assertTrue(
                err.message!!.contains("not a valid generated API name") &&
                    err.message!!.contains("'$name'"),
                "expected an identifier diagnostic naming '$name', got: ${err.message}",
            )
        }
    }

    @Test
    fun `edge declared 'copy' collides with the Edges data-class member`() {
        val errors = validate(
            "EdgesCopyOwner" to EdgesCopyOwner(),
            "EdgesCopyTarget" to EdgesCopyTarget(),
        )
        assertCollision(errors, "EdgesCopyOwner.Edges", "copy")
    }

    @Test
    fun `edge whose traversal collides with a fixed query member is rejected`() {
        val errors = validate(
            "QueryClashOwner" to QueryClashOwner(),
            "QueryClashTarget" to QueryClashTarget(),
        )
        assertCollision(errors, "QueryClashOwnerQuery", "queryLimit")
    }

    @Test
    fun `edge declared 'edges' is not rejected for a removed loadEdges helper`() {
        val errors = validate(
            "LoadClashOwner" to LoadClashOwner(),
            "LoadClashTarget" to LoadClashTarget(),
        )
        assertEquals(emptyList(), errors)
    }

    @Test
    fun `mutable properties differing only by an is-prefix collide on the JVM setter`() {
        // Kotlin maps `var isActive` to `setActive(...)` and `var active`
        // to the same signature, so generated mutation surfaces holding
        // both hit a platform declaration clash. Source names differ, so
        // only JVM-signature modelling catches it.
        val errors = validate("IsPrefix" to IsPrefix())
        assertCollision(errors, "IsPrefixMutation", "setActive(…)")
    }

    @Test
    fun `read-only properties differing only by an is-prefix do not collide`() {
        // The getters are `getActive()` and `isActive()` — distinct. Only
        // settable members share a signature, so an entity-only pair must
        // not be rejected.
        val errors = validate("IsPrefixImmutable" to IsPrefixImmutable())
        assertTrue(
            errors.none { "setActive" in it },
            "immutable is-prefix pair must not report a setter collision: $errors",
        )
    }

    // ──────────────────────────────────────────────────────────────
    // Negative test: existing valid schemas should not raise false
    // positives. Mirrors the acceptance criterion
    // "Existing valid schemas continue to pass without renaming."
    // ──────────────────────────────────────────────────────────────

    @Test
    fun `clean schema with scalars + FK + edges produces no collisions`() {
        class Author : EntSchema("authors", clientName = "authors") {
            override fun id() = EntId.long()
            val name by string("name")
        }
        class Post : EntSchema("posts", clientName = "posts") {
            override fun id() = EntId.long()
            val title by string("title")
            val createdAt by time("created_at").immutable()
            val author by belongsTo<Author>("author")
        }

        val errors = validate("Author" to Author(), "Post" to Post())
        assertEquals(emptyList(), errors)
    }
}

// Companion-ref collision fixtures. `CompanionPost.author` is a
// belongsTo, so its implicit FK companion ref is `authorId`; the
// hasMany edge is *declared* `authorId`, so its companion edge ref is
// `authorId` too. Same artifact, same member name.
//
// These live at file level because the hasMany/belongsTo pair is
// mutually recursive, which local classes cannot express.
private class CompanionAuthor : EntSchema("companion_authors", clientName = "companionAuthors") {
    override fun id() = EntId.long()
}

private class CompanionPost : EntSchema("companion_posts", clientName = "companionPosts") {
    override fun id() = EntId.long()
    val author by belongsTo<CompanionAuthor>("author")
    val authorId by hasMany<CompanionReader>("post_readers")
}

private class CompanionReader : EntSchema("companion_readers", clientName = "companionReaders") {
    override fun id() = EntId.long()
    val post by belongsTo<CompanionPost>("post_readers")
}

// Edges-class collision fixtures. Edge members are the schema author's
// Kotlin declarations, so an edge named after a data-class synthesized
// member reaches `${Entity}Edges` and breaks generated source.
private class EdgesCopyTarget : EntSchema("edges_copy_targets", clientName = "edgesCopyTargets") {
    override fun id() = EntId.long()
    val owner by belongsTo<EdgesCopyOwner>("owner")
}

private class EdgesCopyOwner : EntSchema("edges_copy_owners", clientName = "edgesCopyOwners") {
    override fun id() = EntId.long()
    // `copy` is synthesized on the Edges data class.
    val copy by hasMany<EdgesCopyTarget>("owner")
}

// Regression fixture for an edge whose load method used to collide with
// the removed generated `loadEdges` helper.
private class LoadClashTarget : EntSchema("load_clash_targets", clientName = "loadClashTargets") {
    override fun id() = EntId.long()
    val owner by belongsTo<LoadClashOwner>("owner").inverse(LoadClashOwner::edges)
}

private class LoadClashOwner : EntSchema("load_clash_owners", clientName = "loadClashOwners") {
    override fun id() = EntId.long()
    val edges by hasMany<LoadClashTarget>("owner")
}

// Query-artifact collision fixture. An edge declared `limit` generates
// `queryLimit`, which collides with the query's fixed bounds property.
private class QueryClashTarget : EntSchema("query_clash_targets", clientName = "queryClashTargets") {
    override fun id() = EntId.long()
    val owner by belongsTo<QueryClashOwner>("owner").inverse(QueryClashOwner::limit)
}

private class QueryClashOwner : EntSchema("query_clash_owners", clientName = "queryClashOwners") {
    override fun id() = EntId.long()
    val limit by hasMany<QueryClashTarget>("owner")
}

private class IsPrefix : EntSchema("is_prefix", clientName = "isPrefixes") {
    override fun id() = EntId.long()
    val active by bool("active")
    val isActive by bool("is_active")
}

// Same pair, but immutable — create-only, never settable after create,
// so the update surfaces never declare them as `var`.
private class IsPrefixImmutable : EntSchema("is_prefix_imm", clientName = "isPrefixImmutables") {
    override fun id() = EntId.long()
    val label by string("label")
}
