package entkt.codegen

import entkt.schema.EntId
import entkt.schema.EntSchema
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.fail

/**
 * end-to-end coverage for generated-member collision checks's
 * generated-member-name collision detection. Exercises
 * `SchemaInspector.validate` over schemas that should and should
 * not produce a member-collision diagnostic.
 *
 * Negative-test pattern: schemas that today pass the existing
 * column-collision check (which fires during finalize()) but
 * trip the new member-collision check.
 */
class MemberCollisionValidationTest {

    private fun validate(vararg schemas: Pair<String, EntSchema>): List<String> {
        val inputs = schemas.map { SchemaInput(it.first, it.second) }
        val result = SchemaInspector.validate(inputs)
        return result.errors
    }

    /**
     * Match the generated-member collision checks diagnostic shape. The new format always
     * includes `<artifact> <kind> '<member>' is generated by`,
     * so the substring `is generated by` plus the artifact and
     * quoted member name uniquely identify a manifest-derived
     * diagnostic. This guards against future regressions where
     * a less-precise pass might satisfy a naive `contains` check.
     */
    private fun assertCollision(
        errors: List<String>,
        artifact: String,
        memberName: String,
        message: String = "expected a $artifact.$memberName collision",
    ) {
        val match = errors.firstOrNull {
            it.contains(artifact) && it.contains("'$memberName'") && it.contains("is generated by")
        }
        if (match == null) {
            fail("$message\nGot errors:\n${errors.joinToString("\n") { "  - $it" }}")
        }
    }

    // ──────────────────────────────────────────────────────────────
    // Collision case: field vs. generated unset{Property}() collision
    // ──────────────────────────────────────────────────────────────

    @Test
    fun `field 'unset_name' collides with the unset method generated for field 'name'`() {
        class S : EntSchema("s") {
            override fun id() = EntId.long()
            val name = string("name")
            val unsetName = bool("unset_name")
        }

        val errors = validate("S" to S())
        // The clash lands on the update mutation view (where unset
        // methods live) and on the update builder.
        assertCollision(errors, "SUpdateMutationView", "unsetName")
    }

    // ──────────────────────────────────────────────────────────────
    // Collision case: field named `copy` colliding with
    // data-class synthesized `copy`.
    // ──────────────────────────────────────────────────────────────

    @Test
    fun `field 'copy' collides with the data-class synthesized copy()`() {
        class S : EntSchema("s") {
            override fun id() = EntId.long()
            val copy = string("copy")
        }

        val errors = validate("S" to S())
        assertCollision(errors, "S", "copy")
        // Framework-member hint should be present since `copy`
        // is data-class synthesized.
        val matching = errors.first { "S " in it && "'copy'" in it }
        assertTrue("framework member" in matching, "framework hint expected: $matching")
    }

    // ──────────────────────────────────────────────────────────────
    // Collision case: field that would generate `component1`
    // colliding with the synthesized component function.
    // ──────────────────────────────────────────────────────────────

    @Test
    fun `field 'component1' collides with the data-class synthesized component1()`() {
        class S : EntSchema("s") {
            override fun id() = EntId.long()
            val component1 = string("component1")
            // Some filler to ensure constructor arity reaches >= 1.
            val title = string("title")
        }

        val errors = validate("S" to S())
        assertCollision(errors, "S", "component1")
    }

    // ──────────────────────────────────────────────────────────────
    // Collision case: field named `edges` colliding with entity
    // `edges`. Caught by the manifest now that the old
    // `validateMemberNames` pass has been retired.
    // ──────────────────────────────────────────────────────────────

    @Test
    fun `field 'edges' collides with the fixed entity 'edges' accessor`() {
        class S : EntSchema("s") {
            override fun id() = EntId.long()
            val edges = string("edges")
        }

        val errors = validate("S" to S())
        assertCollision(errors, "S", "edges")
    }
    // Collision case: field whose generated name matches a
    // fixed builder member (`saveOrError`).
    // ──────────────────────────────────────────────────────────────

    @Test
    fun `field 'save_or_error' collides with the fixed builder saveOrError on Create and Update`() {
        class S : EntSchema("s") {
            override fun id() = EntId.long()
            val saveOrError = bool("save_or_error")
        }

        val errors = validate("S" to S())
        // Lands on both SCreate (immutable-or-mutable-doesn't-matter,
        // both have the setter) and SUpdate.
        assertCollision(errors, "SCreate", "saveOrError")
        assertCollision(errors, "SUpdate", "saveOrError")
    }

    // ──────────────────────────────────────────────────────────────
    // Collision case: field named `from_row` colliding with
    // companion `fromRow`. The collision IS real — the entity
    // companion gets per-field column refs alongside the fixed
    // `fromRow()` decoder, both on the same `${Entity}.Companion`
    // artifact.
    // ──────────────────────────────────────────────────────────────

    @Test
    fun `field 'from_row' collides with the companion 'fromRow' decoder`() {
        class S : EntSchema("s") {
            override fun id() = EntId.long()
            val fromRow = string("from_row")
        }

        val errors = validate("S" to S())
        // The column ref `S.Companion.fromRow` (PROPERTY, from
        // the field) clashes with the fixed `S.Companion.fromRow()`
        // function. Manifest detects both on the `S.Companion`
        // artifact.
        assertCollision(errors, "S.Companion", "fromRow")
    }

    // ──────────────────────────────────────────────────────────────
    // Collision case: diagnostic includes the schema name,
    // generated artifact, generated member name, and both sources.
    // ──────────────────────────────────────────────────────────────

    @Test
    fun `diagnostic includes schema name, artifact, member name, and both contributing sources`() {
        class S : EntSchema("s") {
            override fun id() = EntId.long()
            val name = string("name")
            val unsetName = bool("unset_name")
        }

        val errors = validate("S" to S())
        val diag = errors.first { it.contains("SUpdateMutationView") && it.contains("'unsetName'") }
        assertTrue("Schema 'S'" in diag, "Diagnostic should name the schema: $diag")
        assertTrue("SUpdateMutationView" in diag, "Diagnostic should name the artifact: $diag")
        assertTrue("'unsetName'" in diag, "Diagnostic should name the member: $diag")
        assertTrue(
            "field 'unset_name'" in diag,
            "Diagnostic should reference the user-declared field: $diag",
        )
        assertTrue(
            "unset method for field 'name'" in diag,
            "Diagnostic should reference the generated unset method source: $diag",
        )
    }

    // ──────────────────────────────────────────────────────────────
    // Collision case: field named `pending_edges`
    // collides with the fixed `pendingEdges` member on the update
    // mutation view, regardless of whether the schema has any
    // helper-eligible M2M edge. The interface emits the property
    // unconditionally, so a non-M2M schema is just as much at risk
    // as an M2M one.
    // ──────────────────────────────────────────────────────────────

    @Test
    fun `field 'pending_edges' collides with the fixed UpdateMutationView pendingEdges member`() {
        class S : EntSchema("s") {
            override fun id() = EntId.long()
            val pendingEdges = string("pending_edges")
        }

        val errors = validate("S" to S())
        assertCollision(errors, "SUpdateMutationView", "pendingEdges")
    }

    // ──────────────────────────────────────────────────────────────
    // Collision cases are documented as not-V1-
    // triggerable. Schema-level name validation enforces snake_case
    // for both field and edge names; a scalar whose camelCased
    // property would match an implicit FK's `${edgeName}Id`
    // property MUST use the same snake_case column as the FK
    // (e.g. `author_id` ↔ `author_id`), which fails at the
    // column-collision layer before the manifest sees it. The
    // same constraint applies to field-backed FKs in V1 because
    // the FK property derives from the backing column, not yet
    // from a Kotlin val name. Once declaration-name capture ships declaration-name
    // capture, the FK property name can diverge from the column
    // and these cases become triggerable; the manifest already
    // handles them and will add the test cases then.
    // ──────────────────────────────────────────────────────────────

    // ──────────────────────────────────────────────────────────────
    // Collision case: companion edge ref name collides with
    // companion FK column ref name. The implicit FK for
    // `belongsTo<X>("author")` produces a column ref named
    // `authorId` on the companion (toCamelCase("author_id"));
    // a `hasMany` edge declared with name "author_id"
    // (snake_case-valid) produces an edge ref also named
    // `authorId` on the same companion. Both share the
    // `${Schema}.Companion` artifact.
    // (The Edges *class* artifact for non-belongsTo edge accessors
    // is deferred — this test covers the companion-only
    // V1 slice of "edge ref vs FK ref" collisions.)
    // ──────────────────────────────────────────────────────────────

    @Test
    fun `edge ref collides with implicit FK column ref on the companion`() {
        class Author : EntSchema("authors") {
            override fun id() = EntId.long()
        }
        class Reader : EntSchema("readers") {
            override fun id() = EntId.long()
        }
        class Post : EntSchema("posts") {
            override fun id() = EntId.long()
            // Implicit FK: column 'author_id', companion column ref 'authorId'.
            val author = belongsTo<Author>("author")
            // Edge name 'author_id' (snake_case-valid) →
            // companion edge ref `toCamelCase('author_id')` = 'authorId'.
            // Same artifact, same name → collision.
            val readers = hasMany<Reader>("author_id")
        }

        val errors = validate("Author" to Author(), "Reader" to Reader(), "Post" to Post())
        assertCollision(errors, "Post.Companion", "authorId")
    }

    // ──────────────────────────────────────────────────────────────
    // create-hook adapter manifest coverage: the private hook-facing adapter
    // properties (`_beforeSaveView`, `_createMutationView` on
    // Create; `_mutationView`, `_beforeSaveView`,
    // `_capturedPendingEdges` on Update) are reachable as
    // collision targets via declaration-name capture declaration-name capture.
    // Schema column names can't start with `_` (snake_case
    // regex), but Kotlin val names can, and declaration-name capture picks up the
    // val name verbatim — so `val _beforeSaveView = uuid("x");
    // val rel = belongsTo<X>("rel").field(_beforeSaveView)`
    // produces a generated FK property named `_beforeSaveView`
    // that collides with the private adapter.
    // ──────────────────────────────────────────────────────────────

    @Test
    fun `field-backed FK named '_beforeSaveView' collides with the Create adapter`() {
        class T : EntSchema("targets_a") {
            override fun id() = EntId.long()
        }
        class S : EntSchema("schemas_a") {
            override fun id() = EntId.long()
            val _beforeSaveView = long("backing_col")
            val rel = belongsTo<T>("rel").field(_beforeSaveView)
        }

        val errors = validate("T" to T(), "S" to S())
        assertCollision(errors, "SCreate", "_beforeSaveView")
    }

    @Test
    fun `field-backed FK named '_createMutationView' collides with the Create adapter`() {
        class T : EntSchema("targets_b") {
            override fun id() = EntId.long()
        }
        class S : EntSchema("schemas_b") {
            override fun id() = EntId.long()
            val _createMutationView = long("backing_col")
            val rel = belongsTo<T>("rel").field(_createMutationView)
        }

        val errors = validate("T" to T(), "S" to S())
        assertCollision(errors, "SCreate", "_createMutationView")
    }

    @Test
    fun `field-backed FK named '_mutationView' collides with the Update adapter`() {
        class T : EntSchema("targets_c") {
            override fun id() = EntId.long()
        }
        class S : EntSchema("schemas_c") {
            override fun id() = EntId.long()
            val _mutationView = long("backing_col")
            val rel = belongsTo<T>("rel").field(_mutationView)
        }

        val errors = validate("T" to T(), "S" to S())
        assertCollision(errors, "SUpdate", "_mutationView")
    }

    // ──────────────────────────────────────────────────────────────
    // Negative test: existing valid schemas should not raise false
    // positives. Mirrors the acceptance criterion
    // "Existing valid schemas continue to pass without renaming."
    // ──────────────────────────────────────────────────────────────

    @Test
    fun `clean schema with scalars + FK + edges produces no collisions`() {
        class Author : EntSchema("authors") {
            override fun id() = EntId.long()
            val name = string("name")
        }
        class Post : EntSchema("posts") {
            override fun id() = EntId.long()
            val title = string("title")
            val createdAt = time("created_at").immutable()
            val author = belongsTo<Author>("author")
        }

        val errors = validate("Author" to Author(), "Post" to Post())
        assertEquals(emptyList(), errors)
    }
}
