package entkt.codegen

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * verification: the diagnostic formatter produces the
 * sentence shape for diagnostics, and
 * surfaces the framework-member hint when one side of the
 * collision is a fixed member.
 */
class MemberCollisionDiagnosticTest {

    @Test
    fun `two-source collision formats with 'and by'`() {
        val collision = MemberCollision(
            schema = "Article",
            artifact = "ArticleUpdateMutationView",
            name = "unsetWriter",
            sources = listOf(
                GeneratedMember("ArticleUpdateMutationView", "unsetWriter", GeneratedMemberKind.FUNCTION, "unset method for FK edge 'author'"),
                GeneratedMember("ArticleUpdateMutationView", "unsetWriter", GeneratedMemberKind.PROPERTY, "field 'unset_writer'"),
            ),
        )

        val diag = formatMemberCollisionDiagnostic(collision)
        // Matches the contract example shape verbatim modulo the kind
        // hint (which the formatter takes from the first source).
        assertEquals(
            "Schema 'Article': ArticleUpdateMutationView method 'unsetWriter' is generated by unset method for FK edge 'author' and by field 'unset_writer'",
            diag,
        )
    }

    @Test
    fun `three-source collision lists every source via 'conflicting sources'`() {
        val collision = MemberCollision(
            schema = "Post",
            artifact = "PostUpdateMutationView",
            name = "unsetName",
            sources = listOf(
                GeneratedMember("PostUpdateMutationView", "unsetName", GeneratedMemberKind.PROPERTY, "field 'name'"),
                GeneratedMember("PostUpdateMutationView", "unsetName", GeneratedMemberKind.PROPERTY, "field 'unset_name'"),
                GeneratedMember("PostUpdateMutationView", "unsetName", GeneratedMemberKind.FUNCTION, "unset method for FK 'name'"),
            ),
        )

        val diag = formatMemberCollisionDiagnostic(collision)
        assertTrue(diag.contains("3 conflicting sources"), diag)
        assertTrue(diag.contains("field 'name'"), diag)
        assertTrue(diag.contains("field 'unset_name'"), diag)
        assertTrue(diag.contains("unset method for FK 'name'"), diag)
    }

    @Test
    fun `framework-member hint is appended when a fixed-member source is involved`() {
        val collision = MemberCollision(
            schema = "Post",
            artifact = "Post",
            name = "copy",
            sources = listOf(
                GeneratedMember("Post", "copy", GeneratedMemberKind.PROPERTY, "field 'copy'"),
                GeneratedMember("Post", "copy", GeneratedMemberKind.FUNCTION, "data-class synthesized copy"),
            ),
        )

        val diag = formatMemberCollisionDiagnostic(collision)
        assertTrue(diag.contains("fixed framework member"), diag)
        assertTrue(diag.contains("rename the user-declared"), diag)
    }

    @Test
    fun `framework hint is absent when both sources are user-declared`() {
        val collision = MemberCollision(
            schema = "Post",
            artifact = "PostUpdateMutationView",
            name = "unsetAuthor",
            sources = listOf(
                GeneratedMember("PostUpdateMutationView", "unsetAuthor", GeneratedMemberKind.FUNCTION, "unset method for FK 'author'"),
                GeneratedMember("PostUpdateMutationView", "unsetAuthor", GeneratedMemberKind.PROPERTY, "field 'unset_author'"),
            ),
        )

        val diag = formatMemberCollisionDiagnostic(collision)
        assertTrue("fixed framework member" !in diag, diag)
    }

    @Test
    fun `diagnostic includes schema name, artifact name, and member name`() {
        val collision = MemberCollision(
            schema = "Foo",
            artifact = "FooUpdate",
            name = "bar",
            sources = listOf(
                GeneratedMember("FooUpdate", "bar", GeneratedMemberKind.PROPERTY, "field 'bar'"),
                GeneratedMember("FooUpdate", "bar", GeneratedMemberKind.PROPERTY, "field 'bar'"),
            ),
        )

        val diag = formatMemberCollisionDiagnostic(collision)
        assertTrue("Schema 'Foo'" in diag)
        assertTrue("FooUpdate" in diag)
        assertTrue("'bar'" in diag)
    }
}
