@file:OptIn(entkt.query.EntktInternal::class)

package entkt.runtime.repository

import entkt.query.EntktInternal
import entkt.runtime.entity.EntEntity
import entkt.runtime.entity.EntityDescriptor
import entkt.runtime.mutation.CreateMutationDraft
import entkt.runtime.mutation.PendingCreateMutation
import entkt.runtime.mutation.RelationshipLocking
import entkt.runtime.mutation.UpdateConsistency
import entkt.runtime.mutation.UpdateMutationDraft
import entkt.runtime.mutation.execution.CreateManyMutationInput
import entkt.runtime.mutation.execution.MutationExecutor
import entkt.runtime.mutation.execution.MutationOperation
import entkt.runtime.privacy.ViewerContext
import entkt.runtime.query.EntityQueryBuilder
import entkt.runtime.result.MutationResult

/** CREATE entry points for IDs generated by the client or database. */
abstract class GeneratedIdRepository<
    Entity : EntEntity<ID>,
    ID : Any,
    CreateDraft : CreateMutationDraft<Entity>,
    UpdateDraft : UpdateMutationDraft<Entity>,
    Query : EntityQueryBuilder<Entity, Query>,
    RuleClient,
> @EntktInternal protected constructor(
    entity: EntityDescriptor<Entity, ID>,
    mutationExecutor: MutationExecutor,
    defaultUpdateConsistency: UpdateConsistency = UpdateConsistency.ReadCurrent,
    defaultRelationshipLocking: RelationshipLocking = RelationshipLocking.OwnerOnly,
) : EntityRepository<
    Entity, ID, CreateDraft, UpdateDraft, Query, RuleClient,
    GeneratedIdRepository<Entity, ID, CreateDraft, UpdateDraft, Query, RuleClient>,
>(entity, mutationExecutor, defaultUpdateConsistency, defaultRelationshipLocking) {
    final override val self: GeneratedIdRepository<Entity, ID, CreateDraft, UpdateDraft, Query, RuleClient>
        get() = this

    protected abstract val createManyOperation:
        MutationOperation<RuleClient, CreateManyMutationInput<CreateDraft>, List<Entity>>

    /** Construct a fresh draft only; do not resolve defaults, execute hooks, or access storage here. */
    protected abstract fun newCreateDraft(): CreateDraft

    fun create(block: CreateDraft.() -> Unit): PendingCreateMutation<CreateDraft, Entity> =
        pendingCreate(newCreateDraft().apply(block))

    fun createMany(viewerContext: ViewerContext, vararg blocks: CreateDraft.() -> Unit): MutationResult<List<Entity>> =
        executeMutation(
            input = CreateManyMutationInput(viewerContext, blocks.asList(), newDraft = ::newCreateDraft),
            operation = { it.createManyOperation },
        )
}
